//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rio.CleanupSolutionConfiguration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] Configurations {
            get {
                return ((string[])(this["Configurations"]));
            }
            set {
                this["Configurations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] Platforms {
            get {
                return ((string[])(this["Platforms"]));
            }
            set {
                this["Platforms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] ConfigurationsToRemove {
            get {
                return ((string[])(this["ConfigurationsToRemove"]));
            }
            set {
                this["ConfigurationsToRemove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] PlatformsToRemove {
            get {
                return ((string[])(this["PlatformsToRemove"]));
            }
            set {
                this["PlatformsToRemove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldSetNETFrameworkVersion {
            get {
                return ((bool)(this["ShouldSetNETFrameworkVersion"]));
            }
            set {
                this["ShouldSetNETFrameworkVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldPromptNETFrameworkVersionOnCleanup {
            get {
                return ((bool)(this["ShouldPromptNETFrameworkVersionOnCleanup"]));
            }
            set {
                this["ShouldPromptNETFrameworkVersionOnCleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NETFrameworkVersion {
            get {
                return ((string)(this["NETFrameworkVersion"]));
            }
            set {
                this["NETFrameworkVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputDirectory {
            get {
                return ((string)(this["OutputDirectory"]));
            }
            set {
                this["OutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldSetOutputDirectory {
            get {
                return ((bool)(this["ShouldSetOutputDirectory"]));
            }
            set {
                this["ShouldSetOutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string CompanyName {
            get {
                return ((string)(this["CompanyName"]));
            }
            set {
                this["CompanyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldSetCompanyName {
            get {
                return ((bool)(this["ShouldSetCompanyName"]));
            }
            set {
                this["ShouldSetCompanyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Copyright {
            get {
                return ((string)(this["Copyright"]));
            }
            set {
                this["Copyright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldSetCopyright {
            get {
                return ((bool)(this["ShouldSetCopyright"]));
            }
            set {
                this["ShouldSetCopyright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Trademark {
            get {
                return ((string)(this["Trademark"]));
            }
            set {
                this["Trademark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldSetTrademark {
            get {
                return ((bool)(this["ShouldSetTrademark"]));
            }
            set {
                this["ShouldSetTrademark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldAdjustAssemblyAndFileVersion {
            get {
                return ((bool)(this["ShouldAdjustAssemblyAndFileVersion"]));
            }
            set {
                this["ShouldAdjustAssemblyAndFileVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NeutralLanguage {
            get {
                return ((string)(this["NeutralLanguage"]));
            }
            set {
                this["NeutralLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldSetNeutralLanguage {
            get {
                return ((bool)(this["ShouldSetNeutralLanguage"]));
            }
            set {
                this["ShouldSetNeutralLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldAdjustSolutionAndProjectNameToFolderName {
            get {
                return ((bool)(this["ShouldAdjustSolutionAndProjectNameToFolderName"]));
            }
            set {
                this["ShouldAdjustSolutionAndProjectNameToFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldPromptProductNameOnCleanup {
            get {
                return ((bool)(this["ShouldPromptProductNameOnCleanup"]));
            }
            set {
                this["ShouldPromptProductNameOnCleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShouldBuildSetupProjectsInReleaseMode {
            get {
                return ((bool)(this["ShouldBuildSetupProjectsInReleaseMode"]));
            }
            set {
                this["ShouldBuildSetupProjectsInReleaseMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShouldNotBuildSetupProjectsInDebugMode {
            get {
                return ((bool)(this["ShouldNotBuildSetupProjectsInDebugMode"]));
            }
            set {
                this["ShouldNotBuildSetupProjectsInDebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShouldNotBuildTestProjectsInReleaseMode {
            get {
                return ((bool)(this["ShouldNotBuildTestProjectsInReleaseMode"]));
            }
            set {
                this["ShouldNotBuildTestProjectsInReleaseMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShouldBuildTestProjectsInDebugMode {
            get {
                return ((bool)(this["ShouldBuildTestProjectsInDebugMode"]));
            }
            set {
                this["ShouldBuildTestProjectsInDebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WasInitialized {
            get {
                return ((bool)(this["WasInitialized"]));
            }
            set {
                this["WasInitialized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShouldSetProductName {
            get {
                return ((bool)(this["ShouldSetProductName"]));
            }
            set {
                this["ShouldSetProductName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShouldSaveBackupsBeforeCleanup {
            get {
                return ((bool)(this["ShouldSaveBackupsBeforeCleanup"]));
            }
            set {
                this["ShouldSaveBackupsBeforeCleanup"] = value;
            }
        }
    }
}
